name: Ejercicio1

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar Tetsts
        run: pytest test.py
