name: Run Tests on push

on: 
  push:
    branches: 
      - main    
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalr pytest
        run: pup install pytest
      - name: Ejecutar test
        run: pytest test.py
