name: examen-workflow
on:
  push: 
    branches:
      - nueva-caracteristica
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          pythn-version: 3.10
      - name: Instalar dependecias
        run: pip install pytest
      - name: Instalar dependencias
        run: pytest test.py
      - name: Build Docker images
        uses: docker/build-push-actions@v5
        with:
          context: .
          file: Dockerfile
          push: false
